In [50]:
#1.
a= int(input("nhap gia tri a: "))
b=int(input("nhap gia tri b: "))
print(a+b)
print(a*b)
print(a-b)
print(int(a/b))

nhap gia tri a: 4
nhap gia tri b: 4
8
16
0
1


In [51]:
#2.
string = "Hello World"
result= string[2:5]
print(result)

llo


In [52]:
#3.
text = "   Hello World  "
stripped_text = text.strip()
print(f"Sau khi xóa khoảng trắng: '{stripped_text}'")
upper_text = stripped_text.upper()
print(f"Dạng chữ hoa: {upper_text}")
lower_text = stripped_text.lower()
print(f"Dạng chữ thường: {lower_text}")
replaced_text = stripped_text.replace('H', 'J')
print(f"Sau khi thay H thành J: {replaced_text}")

Sau khi xóa khoảng trắng: 'Hello World'
Dạng chữ hoa: HELLO WORLD
Dạng chữ thường: hello world
Sau khi thay H thành J: Jello World


In [53]:
#4.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
if a>b:
  print("Hello World!")

nhap a: 3
nhap b: 2
Hello World!


In [54]:
#5.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
if a==b:
  print("Yes")
else:
  print("No")

nhap a: 2
nhap b: 2
Yes


In [55]:
#6.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
if a==b:
  print("1")
elif a>b:
  print("2")
else:
  print("3")

nhap a: 3
nhap b: 7
3


In [56]:
#7.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
d= int(input("nhap d: "))
if a==b & b==d:
  print("Hello World!!")

nhap a: 5
nhap b: 5
nhap d: 5
Hello World!!


In [57]:
#8.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
c= int(input("nhap c: "))
d= int(input("nhap d: "))
if a==b or c==d:
  print("Hello World!!")

nhap a: 5
nhap b: 5
nhap c: 4
nhap d: 7
Hello World!!


In [58]:
#9.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
print("yes") if a > b else print("no")

nhap a: 2
nhap b: 5
no


In [59]:
#10.
a= int(input("nhap a: "))
b= int(input("nhap b: "))
print("A") if a > b else print("=") if a == b else print("B")

nhap a: 5
nhap b: 2
A


In [60]:
#11.
import numpy as np
arr1=np.arange(10)
arr2=[]
for i in arr1:
  if i % 2 == 0:
    arr2.append(i)
arr2=np.array(arr2)
print(arr2)
print(arr1)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [61]:
#12
import numpy as np
arr = np.arange(1000)
sum = 0
for i in arr:
  if i % 3 == 0 or i % 5 == 0:
    sum = sum + i
print(sum)

233168


In [62]:
#13
a=[1,2,3,4,5,6]
b=[2,4,6,8]
min = len(b) if len(a) > len(b) else len(a)
c = a if len(a)>len(b) else b
for i in range(min):
  c[i]=a[i]+b[i]
print(c)

[3, 6, 9, 12, 5, 6]


In [63]:
#14 a.
import numpy as np
m= int(input("nhap m: "))
n= int(input("nhap n: "))
data = np.random.randn(m, n)
print(data)

nhap m: 3
nhap n: 3
[[-1.01705644  0.00901253  0.63707951]
 [-1.18724461 -0.00993172  0.28901995]
 [-2.33125534 -0.07790273 -1.47527965]]


In [64]:
#14b
import numpy as np
m= int(input("nhap m: "))
n= int(input("nhap n: "))
data = np.random.randn(m, n)
print(data)
k= int(input("nhap k: "))
if m > k >= 0:
  print(data[k])
else:
  print("sai")


nhap m: 2
nhap n: 1
[[1.07406371]
 [0.528297  ]]
nhap k: 4
sai


In [65]:
#14c
import numpy as np
m= int(input("nhap m: "))
n= int(input("nhap n: "))
data = np.random.randn(m, n)
print(data)
k= int(input("nhap k: "))
if n > k >= 0:
  print(data[:,k])
else:
  print("sai")


nhap m: 3
nhap n: 3
[[-0.11831082  0.25575512 -1.12565954]
 [-0.17886167  0.94173272  0.83170615]
 [-0.83487662  1.85716073  0.11347337]]
nhap k: 2
[-1.12565954  0.83170615  0.11347337]


In [66]:
#14d
import numpy as np
m= int(input("nhap m: "))
n= int(input("nhap n: "))
data = np.random.randn(m, n)
print(data)
Sum= np.sum(data, axis=1)
Max= np.argmax(Sum)
print(f"dong co tong lon nhat la: ",data[Max])

nhap m: 3
nhap n: 3
[[ 2.97301632  1.2549258  -0.03352597]
 [-0.95960217  2.47061505  0.94888694]
 [ 0.94293145 -0.18331921  1.59191936]]
dong co tong lon nhat la:  [ 2.97301632  1.2549258  -0.03352597]


In [67]:
#14e
import numpy as np
m= int(input("nhap m: "))
n= int(input("nhap n: "))
data = np.random.randn(m, n)
print(data)
Tich= np.prod(data, axis=1)
Min= np.argmin(Tich)
print(f"dong co tich nho nhat la: ",data[Min])

nhap m: 2
nhap n: 2
[[-1.043769   -0.98203433]
 [ 0.77757627  0.78920969]]
dong co tich nho nhat la:  [0.77757627 0.78920969]
